name: Auto Deploy

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Show branch
        run: |
          echo head_ref= ${{ github.head_ref }}
          echo ref_name= ${{ github.ref_name }}

